/* Blobby pose renderers (no logic side-effects) */
import { BLOBBY, state } from './constants.js';

/** Idle / neutral pose */
export function blobbyStandingFront() {
    const gameChar = state.gameChar;
    stroke(0);
    fill(BLOBBY.COLORS.FEET);
    ellipse(gameChar.x - BLOBBY.DIMENSIONS.BODY_WIDTH * 0.25, gameChar.y - BLOBBY.DIMENSIONS.FEET_HEIGHT / 2, BLOBBY.DIMENSIONS.FEET_WIDTH, BLOBBY.DIMENSIONS.FEET_HEIGHT);
    ellipse(gameChar.x + BLOBBY.DIMENSIONS.BODY_WIDTH * 0.25, gameChar.y - BLOBBY.DIMENSIONS.FEET_HEIGHT / 2, BLOBBY.DIMENSIONS.FEET_WIDTH, BLOBBY.DIMENSIONS.FEET_HEIGHT);
    fill(BLOBBY.COLORS.BODY);
    ellipse(gameChar.x, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT / 2 - BLOBBY.DIMENSIONS.FEET_HEIGHT / 2, BLOBBY.DIMENSIONS.BODY_WIDTH, BLOBBY.DIMENSIONS.BODY_HEIGHT);
    fill(BLOBBY.COLORS.ARM);
    rect(gameChar.x - BLOBBY.DIMENSIONS.BODY_WIDTH / 2, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.4, BLOBBY.DIMENSIONS.ARM_WIDTH, BLOBBY.DIMENSIONS.ARM_LENGTH, 5);
    rect(gameChar.x + BLOBBY.DIMENSIONS.BODY_WIDTH / 2 - BLOBBY.DIMENSIONS.ARM_WIDTH, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.4, BLOBBY.DIMENSIONS.ARM_WIDTH, BLOBBY.DIMENSIONS.ARM_LENGTH, 5);
    noStroke();
    fill(BLOBBY.COLORS.EYE);
    ellipse(gameChar.x - BLOBBY.DIMENSIONS.BODY_WIDTH * 0.2, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.6, BLOBBY.DIMENSIONS.EYE_SIZE, BLOBBY.DIMENSIONS.EYE_SIZE);
    ellipse(gameChar.x + BLOBBY.DIMENSIONS.BODY_WIDTH * 0.2, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.6, BLOBBY.DIMENSIONS.EYE_SIZE, BLOBBY.DIMENSIONS.EYE_SIZE);
    fill(BLOBBY.COLORS.PUPIL);
    ellipse(gameChar.x - BLOBBY.DIMENSIONS.BODY_WIDTH * 0.2, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.6, BLOBBY.DIMENSIONS.PUPIL_SIZE, BLOBBY.DIMENSIONS.PUPIL_SIZE);
    ellipse(gameChar.x + BLOBBY.DIMENSIONS.BODY_WIDTH * 0.2, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.6, BLOBBY.DIMENSIONS.PUPIL_SIZE, BLOBBY.DIMENSIONS.PUPIL_SIZE);
    stroke(BLOBBY.COLORS.PUPIL);
    noFill();
    arc(gameChar.x - BLOBBY.DIMENSIONS.BODY_WIDTH * 0.2, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.65, BLOBBY.DIMENSIONS.PUPIL_SIZE * 2, BLOBBY.DIMENSIONS.PUPIL_SIZE * 2, BLOBBY.EYEBROW_START, BLOBBY.EYEBROW_STOP);
    arc(gameChar.x + BLOBBY.DIMENSIONS.BODY_WIDTH * 0.2, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.65, BLOBBY.DIMENSIONS.PUPIL_SIZE * 2, BLOBBY.DIMENSIONS.PUPIL_SIZE * 2, BLOBBY.EYEBROW_START, BLOBBY.EYEBROW_STOP);
    stroke(BLOBBY.COLORS.MOUTH);
    noFill();
    arc(gameChar.x, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.35, 10, 5, 0, PI);
}

/** Vertical jump / airborne idle */
export function blobbyJumping() {
    const gameChar = state.gameChar;
    stroke(0);
    fill(BLOBBY.COLORS.FEET);
    ellipse(gameChar.x - BLOBBY.DIMENSIONS.BODY_WIDTH * 0.15, gameChar.y - BLOBBY.DIMENSIONS.FEET_HEIGHT / 2 + 5, BLOBBY.DIMENSIONS.FEET_WIDTH * 0.8, BLOBBY.DIMENSIONS.FEET_HEIGHT * 0.8);
    ellipse(gameChar.x + BLOBBY.DIMENSIONS.BODY_WIDTH * 0.15, gameChar.y - BLOBBY.DIMENSIONS.FEET_HEIGHT / 2 + 5, BLOBBY.DIMENSIONS.FEET_WIDTH * 0.8, BLOBBY.DIMENSIONS.FEET_HEIGHT * 0.8);
    fill(BLOBBY.COLORS.BODY);
    ellipse(gameChar.x, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT / 2 - BLOBBY.DIMENSIONS.FEET_HEIGHT / 2, BLOBBY.DIMENSIONS.BODY_WIDTH, BLOBBY.DIMENSIONS.BODY_HEIGHT * 1.1);
    fill(BLOBBY.COLORS.ARM);
    rect(gameChar.x - BLOBBY.DIMENSIONS.BODY_WIDTH / 2 + 2, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.5 - BLOBBY.DIMENSIONS.ARM_LENGTH * 0.5, BLOBBY.DIMENSIONS.ARM_WIDTH, BLOBBY.DIMENSIONS.ARM_LENGTH, 5);
    rect(gameChar.x + BLOBBY.DIMENSIONS.BODY_WIDTH / 2 - BLOBBY.DIMENSIONS.ARM_WIDTH - 2, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.5 - BLOBBY.DIMENSIONS.ARM_LENGTH * 0.5, BLOBBY.DIMENSIONS.ARM_WIDTH, BLOBBY.DIMENSIONS.ARM_LENGTH, 5);
    noStroke();
    fill(BLOBBY.COLORS.EYE);
    ellipse(gameChar.x - BLOBBY.DIMENSIONS.BODY_WIDTH * 0.2, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.6, BLOBBY.DIMENSIONS.EYE_SIZE * 1.2, BLOBBY.DIMENSIONS.EYE_SIZE * 1.2);
    ellipse(gameChar.x + BLOBBY.DIMENSIONS.BODY_WIDTH * 0.2, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.6, BLOBBY.DIMENSIONS.EYE_SIZE * 1.2, BLOBBY.DIMENSIONS.EYE_SIZE * 1.2);
    fill(BLOBBY.COLORS.PUPIL);
    ellipse(gameChar.x - BLOBBY.DIMENSIONS.BODY_WIDTH * 0.2, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.6, BLOBBY.DIMENSIONS.PUPIL_SIZE, BLOBBY.DIMENSIONS.PUPIL_SIZE);
    ellipse(gameChar.x + BLOBBY.DIMENSIONS.BODY_WIDTH * 0.2, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.6, BLOBBY.DIMENSIONS.PUPIL_SIZE, BLOBBY.DIMENSIONS.PUPIL_SIZE);
    stroke(BLOBBY.COLORS.PUPIL);
    noFill();
    arc(gameChar.x - BLOBBY.DIMENSIONS.BODY_WIDTH * 0.2, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.7, BLOBBY.DIMENSIONS.PUPIL_SIZE * 2, BLOBBY.DIMENSIONS.PUPIL_SIZE * 2, BLOBBY.EYEBROW_START, BLOBBY.EYEBROW_STOP);
    arc(gameChar.x + BLOBBY.DIMENSIONS.BODY_WIDTH * 0.2, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.7, BLOBBY.DIMENSIONS.PUPIL_SIZE * 2, BLOBBY.DIMENSIONS.PUPIL_SIZE * 2, BLOBBY.EYEBROW_START, BLOBBY.EYEBROW_STOP);
    noStroke();
    fill(BLOBBY.COLORS.MOUTH);
    ellipse(gameChar.x, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.35, 8, 8);
}

/** Walk cycle facing left */
export function blobbyWalkingLeft() {
    const gameChar = state.gameChar;
    const phase = gameChar.walkCycle;
    const footLift = sin(phase) * 4;
    const rearFootOffset = -sin(phase + PI / 2) * 3;
    stroke(0);
    fill(BLOBBY.COLORS.FEET);
    ellipse(gameChar.x - BLOBBY.DIMENSIONS.BODY_WIDTH * 0.25 + 3, gameChar.y - BLOBBY.DIMENSIONS.FEET_HEIGHT / 2 - footLift, BLOBBY.DIMENSIONS.FEET_WIDTH * 1.1, BLOBBY.DIMENSIONS.FEET_HEIGHT);
    fill(BLOBBY.COLORS.BODY);
    ellipse(gameChar.x, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT / 2 - BLOBBY.DIMENSIONS.FEET_HEIGHT / 2, BLOBBY.DIMENSIONS.BODY_WIDTH, BLOBBY.DIMENSIONS.BODY_HEIGHT);
    fill(BLOBBY.COLORS.FEET);
    ellipse(gameChar.x - BLOBBY.DIMENSIONS.BODY_WIDTH * 0.1 + 3, gameChar.y - BLOBBY.DIMENSIONS.FEET_HEIGHT / 2 - rearFootOffset, BLOBBY.DIMENSIONS.FEET_WIDTH, BLOBBY.DIMENSIONS.FEET_HEIGHT);
    fill(BLOBBY.COLORS.ARM);
    rect(gameChar.x - BLOBBY.DIMENSIONS.BODY_WIDTH / 2 + 20, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.5 - BLOBBY.DIMENSIONS.ARM_LENGTH * 0.5, BLOBBY.DIMENSIONS.ARM_WIDTH, BLOBBY.DIMENSIONS.ARM_LENGTH, 5);
    noStroke();
    fill(BLOBBY.COLORS.EYE);
    ellipse(gameChar.x - BLOBBY.DIMENSIONS.BODY_WIDTH * 0.25, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.6, BLOBBY.DIMENSIONS.EYE_SIZE, BLOBBY.DIMENSIONS.EYE_SIZE);
    fill(BLOBBY.COLORS.PUPIL);
    ellipse(gameChar.x - BLOBBY.DIMENSIONS.BODY_WIDTH * 0.25 - 1, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.6, BLOBBY.DIMENSIONS.PUPIL_SIZE, BLOBBY.DIMENSIONS.PUPIL_SIZE);
    stroke(BLOBBY.COLORS.PUPIL);
    noFill();
    arc(gameChar.x - BLOBBY.DIMENSIONS.BODY_WIDTH * 0.25, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.65, BLOBBY.DIMENSIONS.PUPIL_SIZE * 2, BLOBBY.DIMENSIONS.PUPIL_SIZE * 2, BLOBBY.EYEBROW_START, BLOBBY.EYEBROW_STOP);
    stroke(BLOBBY.COLORS.MOUTH);
    line(gameChar.x - BLOBBY.DIMENSIONS.BODY_WIDTH * 0.3, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.35, gameChar.x - BLOBBY.DIMENSIONS.BODY_WIDTH * 0.1, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.35);
}

/** Walk cycle facing right */
export function blobbyWalkingRight() {
    const gameChar = state.gameChar;
    const phase = gameChar.walkCycle;
    const footLift = sin(phase) * 4;
    const rearFootOffset = -sin(phase + PI / 2) * 3;
    stroke(0);
    fill(BLOBBY.COLORS.FEET);
    ellipse(gameChar.x + BLOBBY.DIMENSIONS.BODY_WIDTH * 0.25 - 3, gameChar.y - BLOBBY.DIMENSIONS.FEET_HEIGHT / 2 - footLift, BLOBBY.DIMENSIONS.FEET_WIDTH * 1.1, BLOBBY.DIMENSIONS.FEET_HEIGHT);
    fill(BLOBBY.COLORS.BODY);
    ellipse(gameChar.x, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT / 2 - BLOBBY.DIMENSIONS.FEET_HEIGHT / 2, BLOBBY.DIMENSIONS.BODY_WIDTH, BLOBBY.DIMENSIONS.BODY_HEIGHT);
    fill(BLOBBY.COLORS.FEET);
    ellipse(gameChar.x + BLOBBY.DIMENSIONS.BODY_WIDTH * 0.1 - 3, gameChar.y - BLOBBY.DIMENSIONS.FEET_HEIGHT / 2 - rearFootOffset, BLOBBY.DIMENSIONS.FEET_WIDTH, BLOBBY.DIMENSIONS.FEET_HEIGHT);
    fill(BLOBBY.COLORS.ARM);
    rect(gameChar.x - BLOBBY.DIMENSIONS.BODY_WIDTH / 2 + 15, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.5 - BLOBBY.DIMENSIONS.ARM_LENGTH * 0.5, BLOBBY.DIMENSIONS.ARM_WIDTH, BLOBBY.DIMENSIONS.ARM_LENGTH, 5);
    noStroke();
    fill(BLOBBY.COLORS.EYE);
    ellipse(gameChar.x + BLOBBY.DIMENSIONS.BODY_WIDTH * 0.25, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.6, BLOBBY.DIMENSIONS.EYE_SIZE, BLOBBY.DIMENSIONS.EYE_SIZE);
    fill(BLOBBY.COLORS.PUPIL);
    ellipse(gameChar.x + BLOBBY.DIMENSIONS.BODY_WIDTH * 0.25 + 1, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.6, BLOBBY.DIMENSIONS.PUPIL_SIZE, BLOBBY.DIMENSIONS.PUPIL_SIZE);
    stroke(BLOBBY.COLORS.PUPIL);
    noFill();
    arc(gameChar.x + BLOBBY.DIMENSIONS.BODY_WIDTH * 0.25, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.65, BLOBBY.DIMENSIONS.PUPIL_SIZE * 2, BLOBBY.DIMENSIONS.PUPIL_SIZE * 2, BLOBBY.EYEBROW_START, BLOBBY.EYEBROW_STOP);
    stroke(BLOBBY.COLORS.MOUTH);
    line(gameChar.x + BLOBBY.DIMENSIONS.BODY_WIDTH * 0.1, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.35, gameChar.x + BLOBBY.DIMENSIONS.BODY_WIDTH * 0.3, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.35);
}

/** Airborne with leftward momentum */
export function blobbyJumpingLeft() {
    const gameChar = state.gameChar;
    stroke(0);
    fill(BLOBBY.COLORS.FEET);
    ellipse(gameChar.x + BLOBBY.DIMENSIONS.BODY_WIDTH * 0.1, gameChar.y - BLOBBY.DIMENSIONS.FEET_HEIGHT / 2 + 5, BLOBBY.DIMENSIONS.FEET_WIDTH * 0.9, BLOBBY.DIMENSIONS.FEET_HEIGHT * 0.9);
    push();
    translate(gameChar.x, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT / 2 - BLOBBY.DIMENSIONS.FEET_HEIGHT / 2);
    rotate(-PI / 12.0);
    fill(BLOBBY.COLORS.BODY);
    ellipse(0, 0, BLOBBY.DIMENSIONS.BODY_WIDTH, BLOBBY.DIMENSIONS.BODY_HEIGHT * 1.05);
    fill(BLOBBY.COLORS.ARM);
    rect(BLOBBY.DIMENSIONS.BODY_WIDTH * 0.2 - BLOBBY.DIMENSIONS.ARM_LENGTH * 1.2, -BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.1 + 10, BLOBBY.DIMENSIONS.ARM_LENGTH * 1.2, BLOBBY.DIMENSIONS.ARM_WIDTH, 5);
    noStroke();
    fill(BLOBBY.COLORS.EYE);
    ellipse(-BLOBBY.DIMENSIONS.BODY_WIDTH * 0.25, -BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.1, BLOBBY.DIMENSIONS.EYE_SIZE * 1.1, BLOBBY.DIMENSIONS.EYE_SIZE * 1.1);
    fill(BLOBBY.COLORS.PUPIL);
    ellipse(-BLOBBY.DIMENSIONS.BODY_WIDTH * 0.25 - 1, -BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.1, BLOBBY.DIMENSIONS.PUPIL_SIZE, BLOBBY.DIMENSIONS.PUPIL_SIZE);
    stroke(BLOBBY.COLORS.PUPIL);
    noFill();
    arc(-BLOBBY.DIMENSIONS.BODY_WIDTH * 0.25, -BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.2, BLOBBY.DIMENSIONS.PUPIL_SIZE * 2, BLOBBY.DIMENSIONS.PUPIL_SIZE * 2, BLOBBY.EYEBROW_START, BLOBBY.EYEBROW_STOP);
    noStroke();
    fill(BLOBBY.COLORS.MOUTH);
    ellipse(-BLOBBY.DIMENSIONS.BODY_WIDTH * 0.4, BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.2, 6, 6);
    pop();
}

/** Airborne with rightward momentum */
export function blobbyJumpingRight() {
    const gameChar = state.gameChar;
    stroke(0);
    fill(BLOBBY.COLORS.FEET);
    ellipse(gameChar.x - BLOBBY.DIMENSIONS.BODY_WIDTH * 0.1, gameChar.y - BLOBBY.DIMENSIONS.FEET_HEIGHT / 2 + 5, BLOBBY.DIMENSIONS.FEET_WIDTH * 0.9, BLOBBY.DIMENSIONS.FEET_HEIGHT * 0.9);
    push();
    translate(gameChar.x, gameChar.y - BLOBBY.DIMENSIONS.BODY_HEIGHT / 2 - BLOBBY.DIMENSIONS.FEET_HEIGHT / 2);
    rotate(PI / 12.0);
    fill(BLOBBY.COLORS.BODY);
    ellipse(0, 0, BLOBBY.DIMENSIONS.BODY_WIDTH, BLOBBY.DIMENSIONS.BODY_HEIGHT * 1.05);
    fill(BLOBBY.COLORS.ARM);
    rect(-BLOBBY.DIMENSIONS.BODY_WIDTH * 0.2, -BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.1 + 10, BLOBBY.DIMENSIONS.ARM_LENGTH * 1.2, BLOBBY.DIMENSIONS.ARM_WIDTH, 5);
    noStroke();
    fill(BLOBBY.COLORS.EYE);
    ellipse(BLOBBY.DIMENSIONS.BODY_WIDTH * 0.25, -BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.1, BLOBBY.DIMENSIONS.EYE_SIZE * 1.1, BLOBBY.DIMENSIONS.EYE_SIZE * 1.1);
    fill(BLOBBY.COLORS.PUPIL);
    ellipse(BLOBBY.DIMENSIONS.BODY_WIDTH * 0.25 + 1, -BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.1, BLOBBY.DIMENSIONS.PUPIL_SIZE, BLOBBY.DIMENSIONS.PUPIL_SIZE);
    stroke(BLOBBY.COLORS.PUPIL);
    noFill();
    arc(BLOBBY.DIMENSIONS.BODY_WIDTH * 0.25, -BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.2, BLOBBY.DIMENSIONS.PUPIL_SIZE * 2, BLOBBY.DIMENSIONS.PUPIL_SIZE * 2, BLOBBY.EYEBROW_START, BLOBBY.EYEBROW_STOP);
    noStroke();
    fill(BLOBBY.COLORS.MOUTH);
    ellipse(-BLOBBY.DIMENSIONS.BODY_WIDTH * -0.4, BLOBBY.DIMENSIONS.BODY_HEIGHT * 0.2, 6, 6);
    pop();
}
